### ISSUE TITLE
Callout Boxes

### ISSUE THREAD

**Issue by jwz2kn** [BluestoneLogic/medium-editor#1]
- Error/Warning Text box
- Info box
- Code (?) box
- Success box

**Comment by eban5** [comment]
The infobox is formatted very similar to the preformatted HTML5 "<pre>" element. We can't duplicate the functionality because it is not using custom code to build pre, instead, I was able to make progress by inserting custom HTML and calling a custom set of JS and CSS for the infobox. Currently, it eats up the text that you select and format as "infobox". Now, only selecting the box and starting to type works.

**Comment by eban5** [comment]
CustomHTML is working. I've created CSS classes for the formatting that inherits from HTML5's `<pre>`. When you select text and then select one of the callout box options (info, warning, and error), the box is inserted in between the text that exists before your selection and your current selection. This was achieved only after commenting out the `range.deleteContents();` from the `CustomHtml.insertHtmlAtCaret` function.
