### ISSUE TITLE
Display BLOB File

### ISSUE THREAD

**Issue by cml5gm** [BluestoneLogic/medium-editor#22]
Ability to preview a referenced blob file.

**Comment by eban5** [comment]
Attached/Embedded or referenced?

_Referenced_ makes this another capability of unfurling, BLOB file instead of hyperlink.
_Attached/embedded_ may or may not require an "Open Office" or LibreOffice server to render the blob file. We need to define the set of extension / BLOB file types we will support initially in this prototype because "any or all BLOB files" would keep us here beyond Sprint 2 and introduce a world of hurt.

**Comment by jwz2kn** [comment]
@eban5 I think the word "preview" indicates that we were going for an unfurling.

**Comment by eban5** [comment]
This issue was moved to BluestoneLogic/df-editor#22
